// ─────────────────────────────────────────────────────────────────
// CHAMPIONS — 146 campeones reales del dataset profesional 2024
// role: rol típico en pro-play (para filtrar por lane)
// ─────────────────────────────────────────────────────────────────

export const CHAMPIONS = [
  // ── TOP ──
  { id: 'Aatrox',       role: 'top' },
  { id: 'Akali',        role: 'top' },
  { id: 'Camille',      role: 'top' },
  { id: "Cho'Gath",     role: 'top' },
  { id: 'Darius',       role: 'top' },
  { id: 'Dr. Mundo',    role: 'top' },
  { id: 'Fiora',        role: 'top' },
  { id: 'Garen',        role: 'top' },
  { id: 'Gnar',         role: 'top' },
  { id: 'Gragas',       role: 'top' },
  { id: 'Gwen',         role: 'top' },
  { id: 'Illaoi',       role: 'top' },
  { id: 'Irelia',       role: 'top' },
  { id: 'Jax',          role: 'top' },
  { id: 'Jayce',        role: 'top' },
  { id: "K'Sante",      role: 'top' },
  { id: 'Kayle',        role: 'top' },
  { id: 'Kennen',       role: 'top' },
  { id: 'Kled',         role: 'top' },
  { id: 'Malphite',     role: 'top' },
  { id: 'Mordekaiser',  role: 'top' },
  { id: 'Olaf',         role: 'top' },
  { id: 'Ornn',         role: 'top' },
  { id: 'Poppy',        role: 'top' },
  { id: 'Renekton',     role: 'top' },
  { id: 'Riven',        role: 'top' },
  { id: 'Rumble',       role: 'top' },
  { id: 'Shen',         role: 'top' },
  { id: 'Sett',         role: 'top' },
  { id: 'Sion',         role: 'top' },
  { id: 'Sylas',        role: 'top' },
  { id: 'Trundle',      role: 'top' },
  { id: 'Tryndamere',   role: 'top' },
  { id: 'Volibear',     role: 'top' },
  { id: 'Wukong',       role: 'top' },

  // ── JNG ──
  { id: 'Amumu',        role: 'jng' },
  { id: "Bel'Veth",     role: 'jng' },
  { id: 'Diana',        role: 'jng' },
  { id: 'Ekko',         role: 'jng' },
  { id: 'Evelynn',      role: 'jng' },
  { id: 'Fiddlesticks', role: 'jng' },
  { id: 'Graves',       role: 'jng' },
  { id: 'Hecarim',      role: 'jng' },
  { id: 'Ivern',        role: 'jng' },
  { id: 'Jarvan IV',    role: 'jng' },
  { id: 'Karthus',      role: 'jng' },
  { id: 'Kayn',         role: 'jng' },
  { id: "Kha'Zix",      role: 'jng' },
  { id: 'Kindred',      role: 'jng' },
  { id: 'Lee Sin',      role: 'jng' },
  { id: 'Lillia',       role: 'jng' },
  { id: 'Maokai',       role: 'jng' },
  { id: 'Nidalee',      role: 'jng' },
  { id: 'Nocturne',     role: 'jng' },
  { id: 'Rammus',       role: 'jng' },
  { id: 'Rengar',       role: 'jng' },
  { id: 'Sejuani',      role: 'jng' },
  { id: 'Taliyah',      role: 'jng' },
  { id: 'Udyr',         role: 'jng' },
  { id: 'Vi',           role: 'jng' },
  { id: 'Viego',        role: 'jng' },
  { id: 'Xin Zhao',     role: 'jng' },
  { id: 'Zac',          role: 'jng' },

  // ── MID ──
  { id: 'Ahri',         role: 'mid' },
  { id: 'Akshan',       role: 'mid' },
  { id: 'Annie',        role: 'mid' },
  { id: 'Aurelion Sol', role: 'mid' },
  { id: 'Azir',         role: 'mid' },
  { id: 'Cassiopeia',   role: 'mid' },
  { id: 'Corki',        role: 'mid' },
  { id: 'Galio',        role: 'mid' },
  { id: 'Heimerdinger', role: 'mid' },
  { id: 'Hwei',         role: 'mid' },
  { id: 'Kassadin',     role: 'mid' },
  { id: 'LeBlanc',      role: 'mid' },
  { id: 'Lissandra',    role: 'mid' },
  { id: 'Lux',          role: 'mid' },
  { id: 'Malzahar',     role: 'mid' },
  { id: 'Naafiri',      role: 'mid' },
  { id: 'Neeko',        role: 'mid' },
  { id: 'Orianna',      role: 'mid' },
  { id: 'Ryze',         role: 'mid' },
  { id: 'Swain',        role: 'mid' },
  { id: 'Syndra',       role: 'mid' },
  { id: 'Talon',        role: 'mid' },
  { id: 'Twisted Fate', role: 'mid' },
  { id: 'Vex',          role: 'mid' },
  { id: 'Viktor',       role: 'mid' },
  { id: 'Vladimir',     role: 'mid' },
  { id: 'Xerath',       role: 'mid' },
  { id: 'Yasuo',        role: 'mid' },
  { id: 'Yone',         role: 'mid' },
  { id: 'Zoe',          role: 'mid' },

  // ── BOT (ADC) ──
  { id: 'Aphelios',     role: 'bot' },
  { id: 'Ashe',         role: 'bot' },
  { id: 'Caitlyn',      role: 'bot' },
  { id: 'Draven',       role: 'bot' },
  { id: 'Ezreal',       role: 'bot' },
  { id: 'Jhin',         role: 'bot' },
  { id: 'Jinx',         role: 'bot' },
  { id: "Kai'Sa",       role: 'bot' },
  { id: 'Kalista',      role: 'bot' },
  { id: "Kog'Maw",      role: 'bot' },
  { id: 'Lucian',       role: 'bot' },
  { id: 'Miss Fortune', role: 'bot' },
  { id: 'Nilah',        role: 'bot' },
  { id: 'Samira',       role: 'bot' },
  { id: 'Sivir',        role: 'bot' },
  { id: 'Smolder',      role: 'bot' },
  { id: 'Tristana',     role: 'bot' },
  { id: 'Twitch',       role: 'bot' },
  { id: 'Varus',        role: 'bot' },
  { id: 'Vayne',        role: 'bot' },
  { id: 'Xayah',        role: 'bot' },
  { id: 'Zeri',         role: 'bot' },
  { id: 'Ziggs',        role: 'bot' },

  // ── SUP ──
  { id: 'Alistar',      role: 'sup' },
  { id: 'Bard',         role: 'sup' },
  { id: 'Blitzcrank',   role: 'sup' },
  { id: 'Brand',        role: 'sup' },
  { id: 'Braum',        role: 'sup' },
  { id: 'Briar',        role: 'sup' },
  { id: 'Janna',        role: 'sup' },
  { id: 'Karma',        role: 'sup' },
  { id: 'Leona',        role: 'sup' },
  { id: 'Lulu',         role: 'sup' },
  { id: 'Milio',        role: 'sup' },
  { id: 'Morgana',      role: 'sup' },
  { id: 'Nami',         role: 'sup' },
  { id: 'Nautilus',     role: 'sup' },
  { id: 'Pantheon',     role: 'sup' },
  { id: 'Pyke',         role: 'sup' },
  { id: 'Rakan',        role: 'sup' },
  { id: 'Rell',         role: 'sup' },
  { id: 'Renata Glasc', role: 'sup' },
  { id: 'Senna',        role: 'sup' },
  { id: 'Seraphine',    role: 'sup' },
  { id: 'Sona',         role: 'sup' },
  { id: 'Soraka',       role: 'sup' },
  { id: 'Tahm Kench',   role: 'sup' },
  { id: 'Taric',        role: 'sup' },
  { id: 'Thresh',       role: 'sup' },
  { id: "Vel'Koz",      role: 'sup' },
  { id: 'Yuumi',        role: 'sup' },
  { id: 'Zilean',       role: 'sup' },
  { id: 'Zyra',         role: 'sup' },
]

export const POSITIONS = ['TOP', 'JNG', 'MID', 'BOT', 'SUP']

export const POSITION_KEYS = {
  TOP: 'top',
  JNG: 'jng',
  MID: 'mid',
  BOT: 'bot',
  SUP: 'sup',
}
